name = "terminal.css"
license = "GPLv3"
licenselink = "https://git.sr.ht/~alexisgeoffrey/hugo-terminal-css/tree/main/item/LICENSE"
description = ""
homepage = "https://sr.ht/~alexisgeoffrey/hugo-terminal-css/"
tags = []
features = []
min_version = "0.98.0"

[author]
  name = "Alexis Geoffrey"
  homepage = "https://alexisgeoffrey.com/"

[original]
  name = "terminal.css"
  homepage = "https://terminalcss.xyz/"
  repo = "https://github.com/Gioni06/terminal.css"
